#!/usr/bin/env node
/**
 * Regenerate the game tables in the root README from `packages/*(/)game.json`.
 *
 *   node scripts/gen-readme.mjs           # rewrite the marked regions
 *   node scripts/gen-readme.mjs --check   # fail if they are out of date
 *
 * Two regions are managed, each delimited by HTML comments so the surrounding
 * prose stays hand-written:
 *
 *   <!-- games:start --> ... <!-- games:end -->   the games table
 *   <!-- urls:start -->  ... <!-- urls:end -->    the deployed-URL table
 *
 * Adding a game means adding a workspace; this script keeps the README in step.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { loadListedGames, repoRoot } from './lib/games.mjs';

const README = join(repoRoot, 'README.md');
const PAGES_ROOT = 'https://savagemanage.github.io/open-games/';

/** Display names for the `stack` tokens used in game.json. */
const STACK_LABELS = {
  react: 'React 18',
  typescript: 'TypeScript',
  phaser3: 'Phaser 3.80',
  vite: 'Vite',
};

const escapeCell = (value) => String(value).replace(/\|/g, '\\|');

function stackLabel(stack) {
  const labels = stack.map((token) => STACK_LABELS[token] ?? token);
  // Vite is the build tool for every game; name it first even though game.json
  // only lists the things that differ between packages.
  return ['Vite', ...labels.filter((label) => label !== 'Vite')].join(' + ');
}

function gameCell(game) {
  const badge = game.status === 'wip' ? ' _(WIP)_' : '';
  const korean = game.titleKo ? ` (${escapeCell(game.titleKo)})` : '';
  return `**${escapeCell(game.title)}**${korean}${badge}`;
}

function gamesTable(games) {
  const rows = games.map(
    (game) =>
      `| [\`packages/${game.slug}\`](./packages/${game.slug}) | ${gameCell(game)} | ${escapeCell(
        game.genre,
      )} | ${stackLabel(game.stack)} | ${escapeCell(game.summary)} |`,
  );
  return ['| Package | Game | Genre | Stack | Summary |', '| --- | --- | --- | --- | --- |', ...rows].join('\n');
}

function urlsTable(games) {
  const rows = games.map(
    (game) => `| \`${PAGES_ROOT}${game.slug}/\` | \`packages/${game.slug}\` |`,
  );
  return [
    '| URL | Source |',
    '| --- | --- |',
    `| \`${PAGES_ROOT}\` | root landing page (\`site/index.template.html\` + \`site/build.mjs\`) |`,
    ...rows,
  ].join('\n');
}

function replaceRegion(text, name, body) {
  const start = `<!-- ${name}:start -->`;
  const end = `<!-- ${name}:end -->`;
  const pattern = new RegExp(`${start}[\\s\\S]*?${end}`);
  if (!pattern.test(text)) {
    throw new Error(`README.md is missing the ${start} / ${end} markers`);
  }
  const generated = `${start}\n<!-- Generated by scripts/gen-readme.mjs from packages/*/game.json. Do not edit by hand. -->\n\n${body}\n\n${end}`;
  return text.replace(pattern, generated);
}

function main() {
  const check = process.argv.includes('--check');
  const games = loadListedGames();
  const before = readFileSync(README, 'utf8');

  let after = replaceRegion(before, 'games', gamesTable(games));
  after = replaceRegion(after, 'urls', urlsTable(games));

  if (after === before) {
    console.log(`[readme] up to date (${games.length} game(s))`);
    return;
  }
  if (check) {
    console.error('[readme] out of date; run `npm run docs:readme` and commit the result.');
    process.exit(1);
  }
  writeFileSync(README, after);
  console.log(`[readme] updated tables for ${games.length} game(s)`);
}

main();
