import { ALLIANCE } from '../config/GameConfig';
import { allianceTechModifiers, techLevelForPoints } from '../config/AllianceConfig';
import type { AllianceState, StatModifiers } from '../types';

/**
 * A thing whose active timer can be brought forward by alliance help. Both
 * BuildingSystem (reduceUpgradeTimer) and ResearchSystem (reduceTimer) satisfy
 * this shape through a tiny adapter, so AllianceSystem never imports either and
 * stays pure + trivially testable. Returns the ms actually shaved off.
 */
export type TimerReducer = (ms: number, now: number) => number;

/**
 * AllianceSystem - a simulated NPC alliance as PURE logic (no Phaser, no
 * servers). It models three faithful WOS alliance mechanics single-player:
 *
 *   - ALLIANCE HELP: a bank of help charges (generated by the AI members). A
 *     help spent on an active build/research timer shaves ALLIANCE.HELP_REDUCTION_MS
 *     off it. {@link help} consumes one charge and applies the reduction via an
 *     injected {@link TimerReducer}, so the timer measurably shortens.
 *   - ALLIANCE TECH: a contribution track — points accumulate toward a tech
 *     level (geometric curve in AllianceConfig) whose {@link modifiers} bundle
 *     lifts the whole hold (economy + army), folded into GameState's combined
 *     StatModifiers so contributing to the alliance genuinely helps.
 *   - MEMBERS: a fixed roster count (ALLIANCE.MEMBER_COUNT) of AI survivors,
 *     surfaced for UI; their names live in i18n.
 *
 * Serializable via toJSON / fromJSON.
 */
export class AllianceSystem {
  private _techPoints: number;
  private _helpsAvailable: number;
  private _helpAccrual: number;
  private _lastContributionAt: number;

  constructor(state?: AllianceState) {
    this._techPoints = state ? Math.max(0, state.techPoints ?? 0) : 0;
    this._helpsAvailable = state
      ? clampHelps(state.helpsAvailable ?? 0)
      : 0;
    this._helpAccrual = state && Number.isFinite(state.helpAccrual) ? Math.max(0, state.helpAccrual ?? 0) : 0;
    this._lastContributionAt = state && Number.isFinite(state.lastContributionAt)
      ? state.lastContributionAt ?? Number.MIN_SAFE_INTEGER
      : Number.MIN_SAFE_INTEGER;
  }

  /** The fixed NPC member count of the simulated alliance. */
  get memberCount(): number {
    return ALLIANCE.MEMBER_COUNT;
  }

  /** Accumulated alliance-tech contribution points. */
  get techPoints(): number {
    return this._techPoints;
  }

  /** Alliance help charges currently available to spend. */
  get helpsAvailable(): number {
    return this._helpsAvailable;
  }

  /** The current alliance-tech level the accumulated points earn. */
  get techLevel(): number {
    return techLevelForPoints(this._techPoints);
  }

  /** Grant `count` alliance help charges (capped at ALLIANCE.MAX_HELPS). */
  grantHelps(count: number): void {
    if (count <= 0) return;
    this._helpsAvailable = clampHelps(this._helpsAvailable + Math.floor(count));
  }

  /**
   * Spend ONE alliance help against an active timer, shaving
   * ALLIANCE.HELP_REDUCTION_MS off it via the injected `reducer`. Returns the ms
   * actually shaved (0 when no charge is available OR the timer is idle, in
   * which case the charge is NOT consumed so it can be used on a real timer).
   */
  help(reducer: TimerReducer, now: number): number {
    if (this._helpsAvailable <= 0) return 0;
    const shaved = reducer(ALLIANCE.HELP_REDUCTION_MS, now);
    if (shaved > 0) this._helpsAvailable -= 1;
    return shaved;
  }

  /** Accrue one help per five minutes of active simulation, preserving fractions. */
  tickActive(deltaMs: number): number {
    if (deltaMs <= 0 || this._helpsAvailable >= ALLIANCE.MAX_HELPS) return 0;
    this._helpAccrual += deltaMs / ALLIANCE.HELP_GEN_INTERVAL_MS;
    const whole = Math.floor(this._helpAccrual);
    if (whole <= 0) return 0;
    const before = this._helpsAvailable;
    this.grantHelps(whole);
    this._helpAccrual -= whole;
    if (this._helpsAvailable >= ALLIANCE.MAX_HELPS) this._helpAccrual = 0;
    return this._helpsAvailable - before;
  }

  /** Paid direct contribution with a one-second debounce. */
  directContribute(resources: import('./ResourceStore').ResourceStore, now: number): boolean {
    if (now - this._lastContributionAt < ALLIANCE.CONTRIBUTION_DEBOUNCE_MS) return false;
    if (!resources.spend({ food: 100, wood: 100 })) return false;
    this._lastContributionAt = now;
    this.contribute(ALLIANCE.DIRECT_CONTRIBUTION_POINTS);
    return true;
  }

  /**
   * Contribute `points` to the alliance-tech track (from the player's activity /
   * spending). Monotonic; raises the tech level when a threshold is crossed.
   * Returns the tech level AFTER the contribution.
   */
  contribute(points: number): number {
    if (points > 0) this._techPoints += points;
    return this.techLevel;
  }

  /**
   * The shared StatModifiers bonus from the current alliance-tech level, folded
   * into GameState's combined bundle so the alliance measurably lifts the hold.
   */
  modifiers(): StatModifiers {
    return allianceTechModifiers(this.techLevel);
  }

  /** Serialize to a plain {@link AllianceState}. */
  toJSON(): AllianceState {
    return {
      techPoints: this._techPoints,
      helpsAvailable: this._helpsAvailable,
      helpAccrual: this._helpAccrual,
      lastContributionAt: this._lastContributionAt,
    };
  }

  /**
   * Restore from a persisted {@link AllianceState}. A missing / malformed value
   * yields a fresh alliance (no points, no helps) so old saves load gracefully.
   */
  static fromJSON(data: AllianceState | undefined | null): AllianceSystem {
    if (!data || typeof data !== 'object') return new AllianceSystem();
    return new AllianceSystem(data);
  }
}

/** Clamp a help count into [0, ALLIANCE.MAX_HELPS] (integer). */
function clampHelps(n: number): number {
  return Math.min(ALLIANCE.MAX_HELPS, Math.max(0, Math.floor(n)));
}
